name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run Specific Job'
        required: false
        default: false
        type: boolean
      custom_message:
        description: 'Enter a custom message'
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    job2:
  runs-on: ubuntu-latest
  if: ${{ fromJSON(github.event.inputs.run_job) }}
  steps:
    - name: Printing Custom Message
      run: echo "${{ github.event.inputs.custom_message }}"

    - name: Printing run-job boolean value
      if: ${{ github.event.inputs.run_job == 'true' || github.event.inputs.run_job }}
      run: echo "run_job input is: ${{ github.event.inputs.run_job }}"

